default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: development1
  username: postgres

test:
  <<: *default
  encoding: unicode
  database: test1
  username: postgres

production:
  <<: *default
